# Use root/example as user/password credentials
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-benefits
    restart: always
    ports:
      - 27020:27017

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb